# Generated by Django 2.1.5 on 2019-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='deskripsi',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
