# Generated by Django 2.1.5 on 2019-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190213_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='deskripsi',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
